spring:
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:postgresql://database.service.local.lan:5432/library
    username: api_library
    password: '{cipher}56a51dd3f995c63d342a5e94a9826d4447b56f66eedf5fdd874dfa7b9101be01c2f45d884d87a70087f96dd1de15eb22'
  jpa:
    database-plataform: org.hibernate.dialect.PosgresSQL94Dialect
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.service.local.lan:7000/auth/realms/library-by-example
