spring:
  datasource:
    url: jdbc:postgresql://database.service.local.lan:5432/catalogue
    username: api_catalogue
    password: '{cipher}4bbe4c6aee9f8f3422352c68688732e6d064f1fd06ea7fac35acc13b05040246b622b045ddd03ff2e6765a0403302ceb'
  jpa:
    database-plataform: org.hibernate.dialect.PosgresSQL94Dialect
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.service.local.lan:7000/auth/realms/library-by-example
